# This workflow will generate documentation for the project and upload it to GitHub.
name: Documentation

on:
  # Trigger the workflow whenever a pull request is opened or updated
  pull_request:
    branches: [ "*" ]

jobs:
  doc:
    strategy:
      matrix:
      # GitHub Actions will create separate jobs for each combination of operating system
        os: [ubuntu-latest, macOS-latest, windows-latest]
    # Run the job on the specified operating system
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get install -y doxygen
        elif [[ "${{ matrix.os }}" == "macOS-latest" ]]; then
          brew install doxygen
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          choco install doxygen -y
        fi

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Upload Documentation
      # Upload the HTML results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: html/
        # This step will upload the generated documentation as an artifact.
        # The artifact can then be downloaded and viewed by anyone who has access to the workflow run.
