# This workflow configuration sets up the environment, installs Python dependencies, runs pytest, and uploads the test results as an artifact.

name: Tests

on:
  # Trigger the workflow whenever a pull request is opened or updated
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    strategy:
      matrix:
        # GitHub Actions will create separate jobs for each combination of operating system and specified Python version.
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.9]
    # Run the job on the specified operating system
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      # Use the actions/setup-python action to set up the specified Python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest==7.3.2 
        pip install pytest-cov
        pip install pytest-html

    - name: Run tests
      # Run pytest to execute tests and generate test results and coverage report
      run: pytest --html=test-results.html --cov-report html:cov-report --cov=${{github.workspace}}/Backend
        
    - name: Upload test results in HTML format
      # Upload the HTML test results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test Results HTML
        path: test-results.html

    - name: Upload coverage report
      # Upload the coverage report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Coverage Report
        path: cov-report/

